just:
  just --choose

create day:
  cargo generate --path ./template --name {{day}}

run day part:
  cd {{day}}; cargo run --bin {{part}} {{day}}

test day part:
  cd {{day}}; cargo test {{part}} -p {{day}}
